/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

/**
 *
 * @author Gabriel Tavares
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameBemVindo = new javax.swing.JInternalFrame();
        jPanelInternalFrame = new javax.swing.JPanel();
        jLabelTituloRelatorios = new javax.swing.JLabel();
        jButtonDenunciasAbertas = new javax.swing.JButton();
        jButtonDenunciasFechadas = new javax.swing.JButton();
        jButtonDenunciasPausadas = new javax.swing.JButton();
        jButtonDenunciasTotais = new javax.swing.JButton();
        jLabelTituloDenunAberta = new javax.swing.JLabel();
        jLabelTituloDenunFechadas = new javax.swing.JLabel();
        jLabelTituloDenunPausadas = new javax.swing.JLabel();
        jLabelTituloDenunTodas = new javax.swing.JLabel();
        jLabelTituloGerenciamentoDenuncias = new javax.swing.JLabel();
        jLabelTituloFeedDenuncias = new javax.swing.JLabel();
        jButtonEditarDenuncias = new javax.swing.JButton();
        jLabelTituloEditarDenuncias = new javax.swing.JLabel();
        jButtonVisualizarDenunciasFeed = new javax.swing.JButton();
        jLabelFundoInternalFrame = new javax.swing.JLabel();
        jLabelPerfilAdministrador = new javax.swing.JLabel();
        jLabelLogoSistema = new javax.swing.JLabel();
        jLabelFundoTelaPrincipal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuItemDenunAbertas = new javax.swing.JMenuItem();
        jMenuItemDenunFechadas = new javax.swing.JMenuItem();
        jMenuItemDenunPausadas = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuVisuDenuncias = new javax.swing.JMenu();
        jMenuItemVisualizarFeed = new javax.swing.JMenuItem();
        jMenuItemEditarDenuncias = new javax.swing.JMenuItem();
        jMenuFerramentas = new javax.swing.JMenu();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemBotaoSairConfirmed = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jInternalFrameBemVindo.setTitle("Bem-Vindo");
        jInternalFrameBemVindo.setVisible(true);
        jInternalFrameBemVindo.getContentPane().setLayout(null);

        jPanelInternalFrame.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelInternalFrame.setLayout(null);

        jLabelTituloRelatorios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTituloRelatorios.setText("Relatórios de Denúncias:");
        jPanelInternalFrame.add(jLabelTituloRelatorios);
        jLabelTituloRelatorios.setBounds(10, 0, 180, 20);

        jButtonDenunciasAbertas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pendente_icon_semfundo.png"))); // NOI18N
        jButtonDenunciasAbertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDenunciasAbertasActionPerformed(evt);
            }
        });
        jPanelInternalFrame.add(jButtonDenunciasAbertas);
        jButtonDenunciasAbertas.setBounds(10, 50, 70, 70);

        jButtonDenunciasFechadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/complete_icon_semfundo.png"))); // NOI18N
        jButtonDenunciasFechadas.setMaximumSize(new java.awt.Dimension(112, 76));
        jButtonDenunciasFechadas.setMinimumSize(new java.awt.Dimension(112, 76));
        jButtonDenunciasFechadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDenunciasFechadasActionPerformed(evt);
            }
        });
        jPanelInternalFrame.add(jButtonDenunciasFechadas);
        jButtonDenunciasFechadas.setBounds(90, 50, 70, 70);

        jButtonDenunciasPausadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pausado_icon_semfundo.png"))); // NOI18N
        jPanelInternalFrame.add(jButtonDenunciasPausadas);
        jButtonDenunciasPausadas.setBounds(170, 50, 70, 70);

        jButtonDenunciasTotais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/all_icon_semfundo.png"))); // NOI18N
        jButtonDenunciasTotais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDenunciasTotaisActionPerformed(evt);
            }
        });
        jPanelInternalFrame.add(jButtonDenunciasTotais);
        jButtonDenunciasTotais.setBounds(250, 50, 70, 70);

        jLabelTituloDenunAberta.setText("Abertas");
        jPanelInternalFrame.add(jLabelTituloDenunAberta);
        jLabelTituloDenunAberta.setBounds(20, 30, 60, 20);

        jLabelTituloDenunFechadas.setText("Fechadas");
        jPanelInternalFrame.add(jLabelTituloDenunFechadas);
        jLabelTituloDenunFechadas.setBounds(100, 30, 70, 20);

        jLabelTituloDenunPausadas.setText("Pausadas");
        jPanelInternalFrame.add(jLabelTituloDenunPausadas);
        jLabelTituloDenunPausadas.setBounds(180, 30, 60, 20);

        jLabelTituloDenunTodas.setText("Todas");
        jPanelInternalFrame.add(jLabelTituloDenunTodas);
        jLabelTituloDenunTodas.setBounds(271, 30, 40, 20);

        jLabelTituloGerenciamentoDenuncias.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTituloGerenciamentoDenuncias.setText("Gerencimento de Denúncias:");
        jPanelInternalFrame.add(jLabelTituloGerenciamentoDenuncias);
        jLabelTituloGerenciamentoDenuncias.setBounds(10, 140, 200, 30);

        jLabelTituloFeedDenuncias.setText("Visualizar Feed");
        jPanelInternalFrame.add(jLabelTituloFeedDenuncias);
        jLabelTituloFeedDenuncias.setBounds(10, 170, 110, 20);

        jButtonEditarDenuncias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/edit_icon_semfundo.png"))); // NOI18N
        jButtonEditarDenuncias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarDenunciasActionPerformed(evt);
            }
        });
        jPanelInternalFrame.add(jButtonEditarDenuncias);
        jButtonEditarDenuncias.setBounds(140, 190, 70, 70);

        jLabelTituloEditarDenuncias.setText("Editar Denúncias");
        jPanelInternalFrame.add(jLabelTituloEditarDenuncias);
        jLabelTituloEditarDenuncias.setBounds(130, 170, 100, 20);

        jButtonVisualizarDenunciasFeed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/feed_icon_semfundo.png"))); // NOI18N
        jPanelInternalFrame.add(jButtonVisualizarDenunciasFeed);
        jButtonVisualizarDenunciasFeed.setBounds(20, 190, 70, 70);

        jLabelFundoInternalFrame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo_internalframe.png"))); // NOI18N
        jPanelInternalFrame.add(jLabelFundoInternalFrame);
        jLabelFundoInternalFrame.setBounds(0, 0, 670, 270);

        jInternalFrameBemVindo.getContentPane().add(jPanelInternalFrame);
        jPanelInternalFrame.setBounds(0, 40, 670, 260);

        jLabelPerfilAdministrador.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelPerfilAdministrador.setText("Perfil Administrador");
        jInternalFrameBemVindo.getContentPane().add(jLabelPerfilAdministrador);
        jLabelPerfilAdministrador.setBounds(490, 0, 180, 40);

        getContentPane().add(jInternalFrameBemVindo);
        jInternalFrameBemVindo.setBounds(0, 30, 680, 340);

        jLabelLogoSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo_portfolio_semfundo.png"))); // NOI18N
        getContentPane().add(jLabelLogoSistema);
        jLabelLogoSistema.setBounds(160, 120, 350, 130);

        jLabelFundoTelaPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo_tela_principal.jpg"))); // NOI18N
        getContentPane().add(jLabelFundoTelaPrincipal);
        jLabelFundoTelaPrincipal.setBounds(-20, 0, 710, 370);

        jMenuRelatorios.setText("Relatórios");

        jMenuItemDenunAbertas.setText("Denúncias Abertas");
        jMenuRelatorios.add(jMenuItemDenunAbertas);

        jMenuItemDenunFechadas.setText("Denúncias Fechadas");
        jMenuItemDenunFechadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDenunFechadasActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuItemDenunFechadas);

        jMenuItemDenunPausadas.setText("Denúncias Pausadas");
        jMenuRelatorios.add(jMenuItemDenunPausadas);

        jMenuItem1.setText("Denúncias Totais");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuItem1);

        jMenuBar1.add(jMenuRelatorios);

        jMenuVisuDenuncias.setText("Visualizar Denúncias");

        jMenuItemVisualizarFeed.setText("Visualizar Feed");
        jMenuVisuDenuncias.add(jMenuItemVisualizarFeed);

        jMenuItemEditarDenuncias.setText("Editar Denuncias");
        jMenuItemEditarDenuncias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditarDenunciasActionPerformed(evt);
            }
        });
        jMenuVisuDenuncias.add(jMenuItemEditarDenuncias);

        jMenuBar1.add(jMenuVisuDenuncias);

        jMenuFerramentas.setText("Ferramentas");
        jMenuBar1.add(jMenuFerramentas);

        jMenuSair.setText("Sair");
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });

        jMenuItemBotaoSairConfirmed.setText("Sair");
        jMenuItemBotaoSairConfirmed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBotaoSairConfirmedActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemBotaoSairConfirmed);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(694, 399));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemDenunFechadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDenunFechadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemDenunFechadasActionPerformed

    private void jButtonDenunciasAbertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDenunciasAbertasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDenunciasAbertasActionPerformed

    private void jButtonDenunciasFechadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDenunciasFechadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDenunciasFechadasActionPerformed

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed
       
    }//GEN-LAST:event_jMenuSairActionPerformed

    private void jMenuItemBotaoSairConfirmedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBotaoSairConfirmedActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemBotaoSairConfirmedActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
      TelaDashboard dash = new TelaDashboard();
        dash.setVisible(true);
        dispose();  
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButtonDenunciasTotaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDenunciasTotaisActionPerformed
        TelaDashboard dash = new TelaDashboard();
        dash.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonDenunciasTotaisActionPerformed

    private void jButtonEditarDenunciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarDenunciasActionPerformed
        TelaEditarDenuncias editdenun = new TelaEditarDenuncias();
        editdenun.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonEditarDenunciasActionPerformed

    private void jMenuItemEditarDenunciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditarDenunciasActionPerformed
        TelaEditarDenuncias editdenun = new TelaEditarDenuncias();
        editdenun.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemEditarDenunciasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDenunciasAbertas;
    private javax.swing.JButton jButtonDenunciasFechadas;
    private javax.swing.JButton jButtonDenunciasPausadas;
    private javax.swing.JButton jButtonDenunciasTotais;
    private javax.swing.JButton jButtonEditarDenuncias;
    private javax.swing.JButton jButtonVisualizarDenunciasFeed;
    private javax.swing.JInternalFrame jInternalFrameBemVindo;
    private javax.swing.JLabel jLabelFundoInternalFrame;
    private javax.swing.JLabel jLabelFundoTelaPrincipal;
    private javax.swing.JLabel jLabelLogoSistema;
    private javax.swing.JLabel jLabelPerfilAdministrador;
    private javax.swing.JLabel jLabelTituloDenunAberta;
    private javax.swing.JLabel jLabelTituloDenunFechadas;
    private javax.swing.JLabel jLabelTituloDenunPausadas;
    private javax.swing.JLabel jLabelTituloDenunTodas;
    private javax.swing.JLabel jLabelTituloEditarDenuncias;
    private javax.swing.JLabel jLabelTituloFeedDenuncias;
    private javax.swing.JLabel jLabelTituloGerenciamentoDenuncias;
    private javax.swing.JLabel jLabelTituloRelatorios;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFerramentas;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemBotaoSairConfirmed;
    private javax.swing.JMenuItem jMenuItemDenunAbertas;
    private javax.swing.JMenuItem jMenuItemDenunFechadas;
    private javax.swing.JMenuItem jMenuItemDenunPausadas;
    private javax.swing.JMenuItem jMenuItemEditarDenuncias;
    private javax.swing.JMenuItem jMenuItemVisualizarFeed;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JMenu jMenuVisuDenuncias;
    private javax.swing.JPanel jPanelInternalFrame;
    // End of variables declaration//GEN-END:variables
}
