/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

/**
 *
 * @author Gabriel Tavares
 */
public class TelaDashboard extends javax.swing.JFrame {

    /**
     * Creates new form TelaDashboard
     */
    public TelaDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonFecharDashboard = new javax.swing.JButton();
        jLabelDashboardImagem = new javax.swing.JLabel();
        jLabelFundoTelaDash = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonFecharDashboard.setText("Fechar");
        jButtonFecharDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharDashboardActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFecharDashboard);
        jButtonFecharDashboard.setBounds(660, 10, 72, 22);

        jLabelDashboardImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/dashboard.png"))); // NOI18N
        getContentPane().add(jLabelDashboardImagem);
        jLabelDashboardImagem.setBounds(-10, 30, 770, 460);

        jLabelFundoTelaDash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo_tela_dash.png"))); // NOI18N
        getContentPane().add(jLabelFundoTelaDash);
        jLabelFundoTelaDash.setBounds(-3, 0, 750, 500);

        setSize(new java.awt.Dimension(763, 509));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFecharDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharDashboardActionPerformed
        TelaPrincipal telaprincip = new TelaPrincipal();
        telaprincip.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonFecharDashboardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFecharDashboard;
    private javax.swing.JLabel jLabelDashboardImagem;
    private javax.swing.JLabel jLabelFundoTelaDash;
    // End of variables declaration//GEN-END:variables
}
