/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

/**
 *
 * @author Gabriel Tavares
 */
public class TelaEditarDenuncias extends javax.swing.JFrame {

    /**
     * Creates new form TelaEditarDenuncias
     */
    public TelaEditarDenuncias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFundoListaDenuncias = new javax.swing.JLabel();
        jLabelTituloDenuncias = new javax.swing.JLabel();
        jButtonVoltarTelaPrincipal = new javax.swing.JButton();
        jLabelFundoBuscaDenuncias = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelFundoListaDenuncias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lista_denuncias.png"))); // NOI18N
        getContentPane().add(jLabelFundoListaDenuncias);
        jLabelFundoListaDenuncias.setBounds(0, 180, 890, 340);

        jLabelTituloDenuncias.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTituloDenuncias.setText("Gerenciamento de Denúncias");
        getContentPane().add(jLabelTituloDenuncias);
        jLabelTituloDenuncias.setBounds(20, 10, 260, 25);

        jButtonVoltarTelaPrincipal.setText("Voltar");
        jButtonVoltarTelaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarTelaPrincipalActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltarTelaPrincipal);
        jButtonVoltarTelaPrincipal.setBounds(800, 10, 90, 30);

        jLabelFundoBuscaDenuncias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/busca_denuncias_att.png"))); // NOI18N
        getContentPane().add(jLabelFundoBuscaDenuncias);
        jLabelFundoBuscaDenuncias.setBounds(0, -60, 920, 400);

        setSize(new java.awt.Dimension(914, 485));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarTelaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarTelaPrincipalActionPerformed
        TelaPrincipal telaprincip = new TelaPrincipal();
        telaprincip.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonVoltarTelaPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEditarDenuncias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEditarDenuncias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEditarDenuncias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEditarDenuncias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEditarDenuncias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonVoltarTelaPrincipal;
    private javax.swing.JLabel jLabelFundoBuscaDenuncias;
    private javax.swing.JLabel jLabelFundoListaDenuncias;
    private javax.swing.JLabel jLabelTituloDenuncias;
    // End of variables declaration//GEN-END:variables
}
